### PR TITLE
Cubic interp

### PR DESCRIPTION
**Pull request by dpwe**
This is supposed to include the cubic table interp, used for sine and impulse -> PWM.

### CODE REVIEW

**Comment by dpwe** [comment]
Apparently also includes the soft clip changes.

**Comment by dpwe** [comment]
There's a bug where the square wave glitches - forgets its phase every second or so.  Am investigating.

**Comment by dpwe** [comment]
"Bug" was just overruns, I think.  It's much harder to control the peak amplitudes of the band limited waveforms, spent a while trying to fix this.  It causes problems when using them as LFO, where the absolute value is very significant.  I think it's close to correct.  TRIANGLE supports DUTY modulation.

I think there's a problem where the band limited oscillators take a few cycles (~10) to stabilize their average levels -- basically, the state variable(s) of the integration LPFs has to settle; I start them at zero because I haven't figured out what the target value should be, although probably I could.  This doesn't matter much for audio oscillators (I think), but with very slow LFOs, this can generate an audible change (since they can take ~seconds to settle).

**Comment by bwhitman** [comment]
Could we "prime" the BLOs a bit outside of audio-rate? Like, just run the render() call for a few cycles every time frequency is changed?

**Comment by dpwe** [comment]
That could work. But it's shameful not to be able to predict the correct initial value for the state.  I plan to do some experiments with a Python simulation.

Also, it's crazy wasteful to run the LFOs at audio-rate (given, I think, we only sample them once per block).  Maybe we should parameterize the oscillators by the sampling rate?  Would make the code look cleaner anyway.

**Pull request merged**
